apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica56-deploy
spec:
  selector:
    matchLabels:
      app: practica56
  replicas: 1
  template:
    metadata:
      labels:
        app: practica56
    spec:
      containers:
        - name: practica56-container
          image: index.docker.io/machacamoya/pruebas-openshift:practica56-v1.0
          volumeMounts:
            - mountPath: /logs/
              name: practica56-log
              readOnly: false
            - mountPath: /config/
              name: cnfmap-practica56
              readOnly: true
            - mountPath: /secret/ 
              name: application-sensitive-config
              readOnly: true
          workingDir: /home/wlp
      volumes:
        - name: practica56-log
          persistentVolumeClaim: 
            claimName: log-pvc
            readOnly: false
        - name: cnfmap-practica56
          configMap:
            name: cnfmap-practica56
        - name: application-sensitive-config
          secret:
            secretName: application-sensitive-config 
